// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxWCtGFRHW4kCIFfwCLS9rvTIj2NUuDvA',
    appId: '1:995158202439:web:75ebcce13fb8191c5f3962',
    messagingSenderId: '995158202439',
    projectId: 'maqcshalminecontrol',
    authDomain: 'maqcshalminecontrol.firebaseapp.com',
    storageBucket: 'maqcshalminecontrol.firebasestorage.app',
    measurementId: 'G-VNLXZ3JEM5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCO5TeL-hPFlqxKws8IhA1nAey3clbO2b4',
    appId: '1:995158202439:android:f8ac2ec8dc2880b65f3962',
    messagingSenderId: '995158202439',
    projectId: 'maqcshalminecontrol',
    storageBucket: 'maqcshalminecontrol.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDowcNWK84RZL36CyujI0Ye3IbMRn9jY7w',
    appId: '1:995158202439:ios:12f5a7b179c215195f3962',
    messagingSenderId: '995158202439',
    projectId: 'maqcshalminecontrol',
    storageBucket: 'maqcshalminecontrol.firebasestorage.app',
    iosBundleId: 'com.example.intento3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDowcNWK84RZL36CyujI0Ye3IbMRn9jY7w',
    appId: '1:995158202439:ios:12f5a7b179c215195f3962',
    messagingSenderId: '995158202439',
    projectId: 'maqcshalminecontrol',
    storageBucket: 'maqcshalminecontrol.firebasestorage.app',
    iosBundleId: 'com.example.intento3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxWCtGFRHW4kCIFfwCLS9rvTIj2NUuDvA',
    appId: '1:995158202439:web:7cdc7c81c65744945f3962',
    messagingSenderId: '995158202439',
    projectId: 'maqcshalminecontrol',
    authDomain: 'maqcshalminecontrol.firebaseapp.com',
    storageBucket: 'maqcshalminecontrol.firebasestorage.app',
    measurementId: 'G-QZVQVHEH9B',
  );
}
